### ISSUE TITLE
panic if devices in config file is empty (interface_description_regex)

### ISSUE THREAD

**Issue by kakkotetsu** [czerwonk/junos_exporter#163]
when `-config.ignore-targets=true` and `devices:` in config file is empty, it panic !!

panic syslog is below, 

```
2021-10-21T16:43:32.625343+09:00 [kf1-prom000][junos_exporter][err] time="2021-10-21T07:43:32Z" level=info msg="Closing connections to devices"
2021-10-21T16:43:35.792088+09:00 [kf1-prom000][junos_exporter][err] time="2021-10-21T07:43:35Z" level=info msg="Loading config from /config.yml"
2021-10-21T16:43:35.793436+09:00 [kf1-prom000][junos_exporter][err] time="2021-10-21T07:43:35Z" level=info msg="Starting JunOS exporter (Version: 0.9.12)\n"
2021-10-21T16:43:35.793635+09:00 [kf1-prom000][junos_exporter][err] time="2021-10-21T07:43:35Z" level=info msg="Listening for /metrics on :9326\n"
2021-10-21T16:44:20.031899+09:00 [kf1-prom000][junos_exporter][err] 2021/10/21 07:44:20 http: panic serving 172.18.0.1:40348: runtime error: index out of range [0] with length 0
2021-10-21T16:44:20.032298+09:00 [kf1-prom000][junos_exporter][err] goroutine 20 [running]:
2021-10-21T16:44:20.032298+09:00 [kf1-prom000][junos_exporter][err] net/http.(*conn).serve.func1()
2021-10-21T16:44:20.032705+09:00 [kf1-prom000][junos_exporter][err] #011/usr/local/go/src/net/http/server.go:1801 +0xb9
2021-10-21T16:44:20.032705+09:00 [kf1-prom000][junos_exporter][err] panic({0x8e94a0, 0xc0002ca1c8})
2021-10-21T16:44:20.033021+09:00 [kf1-prom000][junos_exporter][err] #011/usr/local/go/src/runtime/panic.go:1047 +0x266
2021-10-21T16:44:20.033281+09:00 [kf1-prom000][junos_exporter][err] main.newJunosCollector({0xc0000b4230, 0x1, 0x91a61c}, 0x2, {0x0, 0x0})
2021-10-21T16:44:20.033281+09:00 [kf1-prom000][junos_exporter][err] #011/go/junos_exporter/junos_collector.go:53 +0x38b
2021-10-21T16:44:20.033281+09:00 [kf1-prom000][junos_exporter][err] main.handleMetricsRequest({0x9c83b8, 0xc0001760e0}, 0xc00016e200)
2021-10-21T16:44:20.033281+09:00 [kf1-prom000][junos_exporter][err] #011/go/junos_exporter/main.go:279 +0x1ed
2021-10-21T16:44:20.034096+09:00 [kf1-prom000][junos_exporter][err] net/http.HandlerFunc.ServeHTTP(0x0, {0x9c83b8, 0xc0001760e0}, 0x0)
2021-10-21T16:44:20.034327+09:00 [kf1-prom000][junos_exporter][err] #011/usr/local/go/src/net/http/server.go:2046 +0x2f
2021-10-21T16:44:20.034516+09:00 [kf1-prom000][junos_exporter][err] net/http.(*ServeMux).ServeHTTP(0xc0000b26cd, {0x9c83b8, 0xc0001760e0}, 0xc00016e200)
2021-10-21T16:44:20.034731+09:00 [kf1-prom000][junos_exporter][err] #011/usr/local/go/src/net/http/server.go:2424 +0x149
2021-10-21T16:44:20.034974+09:00 [kf1-prom000][junos_exporter][err] net/http.serverHandler.ServeHTTP({0xc0001743c0}, {0x9c83b8, 0xc0001760e0}, 0xc00016e200)
2021-10-21T16:44:20.035217+09:00 [kf1-prom000][junos_exporter][err] #011/usr/local/go/src/net/http/server.go:2878 +0x43b
2021-10-21T16:44:20.035555+09:00 [kf1-prom000][junos_exporter][err] net/http.(*conn).serve(0xc00016c820, {0x9ca398, 0xc0001742d0})
2021-10-21T16:44:20.035742+09:00 [kf1-prom000][junos_exporter][err] #011/usr/local/go/src/net/http/server.go:1929 +0xb08
2021-10-21T16:44:20.035932+09:00 [kf1-prom000][junos_exporter][err] created by net/http.(*Server).Serve
...
``` 

Maybe it need to check nil or `config.ignore-targets` parameter check in the following places.

https://github.com/czerwonk/junos_exporter/blob/master/junos_collector.go#L53

**Comment by fstolba** [comment]
It's possible to workaround this by specifying `interface_description_regex` in the config file a la

`interface_description_regex: '[\s(=[^,\]]+)?[,]]'`

**Comment by kakkotetsu** [comment]
#176 fixed this issue !
